[global]
disableWidgetStateDuplicationWarning = true


[theme]
primaryColor="#333367"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#E0E2E6"
textColor="#262730"
font="sans serif"

[browser]
gatherUsageStats = false